### ISSUE TITLE
Application debug

### ISSUE THREAD

**Issue by woodyjon** [LedgerHQ/ledger-dev-doc#12]
Trying to follow the steps here to debug an app: https://ledger.readthedocs.io/en/latest/userspace/debugging.html

When I follow the instructions and add a PRINTF in the code, when I try to load the app, I get the following error:
```
undefined reference to `screen_printf'
```
I gess I am missing something. I would appreciate your help on this.

Thank you.

**Comment by PhilippeBonnaz** [comment]
Did you update your app makefile with adding the following line
```sh
DEFINES   += HAVE_SPRINTF HAVE_PRINTF PRINTF=screen_printf
```
And commenting the following line
```sh
DEFINES   += PRINTF\(...\)=
```

**Comment by woodyjon** [comment]
How would you change the sample app blue-app-helloworld for printing something at the start of the app?
Just change the DEFINES in makefile and add for example "PRINTF("Hello !);" at the beginning of sample_main()?
Because if I do that, I have above error.

**Comment by woodyjon** [comment]
Yes, I use the sdk nanos-1421

**Comment by woodyjon** [comment]
Did you also add a PRINTF instance in the code?
When I add a PRINTF, I get the error
```
Repos/blue-sample-apps/blue-app-helloworld/src/main.c:214: undefined reference to `screen_printf'
```

**Comment by PhilippeBonnaz** [comment]
Yes I did.
Did you try to run 'make clean' before trying to build ?

**Comment by woodyjon** [comment]
That was it ;-)
I could compile and load successfully after `make clean`. Thank you very much.

**Comment by woodyjon** [comment]
usbtool still does not print anything though. Where in the code can you safely add a PRINTF? It is not clear to me from the doc page.
And with usbtool logging, when I start an app on the ledger, I get `USB error: error sending control message: Protocol error`, but I do not have any PRINTF printing.

And thank you again and sorry for the time wasted because of `make clean`.

**Comment by PhilippeBonnaz** [comment]
No worries ;)
PRINTF has to be called between two successive io_exchange() calls
Try to call PRINTF on line 233 for example, it should work

**Comment by woodyjon** [comment]
If I run `./usbtool -w list`, it successfully lists my device: `BID=0x01 VID=0x2c97 PID=0x0001 vendor="Ledger" product="Nano S" serial="0001"`
But with `./usbtool -v 0x2c97 log`, I have `USB error: error sending control message: Protocol error` when I launch the app on the ledger.

**Comment by woodyjon** [comment]
Indeed, that one works!
A big thank you!
