### ISSUE TITLE
Cannot join the Slack workspace

### ISSUE THREAD

**Issue by nnkken** [LedgerHQ/ledger-dev-doc#23]
Hi, I'm a developer and I've read the document.

The document stated that `External developer teams are welcome on Ledger’s Developer Slack. This is the place to get technical support, to discuss Ledger’s tech stack, and more broadly to get in touch with us.`

However, I found that I need to be invited before I can join the Slack workspace, and I cannot find any other contact methods for developers.

I also found the Slack Trello board, which gives out http://slack.ledger.co/ for Developer Slack registration, but the link no longer works now.

So how should I join the Slack workspace?

(I think it could be count as a bug in the document?)

**Comment by atlaschiew** [comment]
i face the same like @nnkken ,but your question was back to last year. may i know have you found d answer?

**Comment by FabriceDautriat** [comment]
Hello,

Thank you for pointing that out, and sorry for the late reply.

To get access you can use [this link](https://join.slack.com/t/ledger-dev/shared_invite/zt-hhm5hmea-JRWWIaZhLPxNCT8bPhAXHg), but it won't be valid after 30 days.

If the link is not valid anymore, please contact the customer success team to request access : https://support.ledger.com/hc/en-us/requests/new
