### ISSUE TITLE
How to add erc20 token to the list on assets supported by Ledger?

### ISSUE THREAD

**Issue by Vasilii79** [LedgerHQ/ledger-dev-doc#38]
Hi, kindly inform me how to add ERC20 token into the Ledger's list of supported cryptocurrency assets: https://www.ledger.com/supported-crypto-assets/ ? 

Thanks in advance!

**Comment by FabriceDautriat** [comment]
You can request the addition by opening a ticket to our customer success team. 

But since you are here already, you can share the smart contract address with me and I'll review it.

**Comment by Vasilii79** [comment]
> You can request the addition by opening a ticket to our [customer success team](https://support.ledger.com/hc/en-us/requests/new).
> 
> But since you are here already, you can share the smart contract address with me and I'll review it.

Hi! Here is the token's smart contract address link: https://etherscan.io/token/0x3d371413dd5489f3a04c07c0c2ce369c20986ceb

Also, if it could help with your review, we have already successfully merged our Pool requests (to add token) to MEW and Trezor
https://github.com/MyEtherWallet/ethereum-lists/pull/1668
https://github.com/ethereum-lists/tokens/pull/436

Thanks in advance!

**Comment by Vasilii79** [comment]
> You can request the addition by opening a ticket to our [customer success team](https://support.ledger.com/hc/en-us/requests/new).
> 
> But since you are here already, you can share the smart contract address with me and I'll review it.

Hi, kindly inform have you reviewed our application (above)?

**Comment by Vasilii79** [comment]
> You can request the addition by opening a ticket to our [customer success team](https://support.ledger.com/hc/en-us/requests/new).
> 
> But since you are here already, you can share the smart contract address with me and I'll review it.

Hello, could you please inform have you reviewed our application (above)?

**Comment by FabriceDautriat** [comment]
It should be supported already. See https://github.com/LedgerHQ/ledgerjs/blob/56a9227fceb5f8b92f5ae77df0cdc82e5891608b/packages/cryptoassets/data/erc20.js#L1680

Please send your token to your ETH address to see them appear on Ledger Live.

**Comment by Vasilii79** [comment]
> It should be supported already. See https://github.com/LedgerHQ/ledgerjs/blob/56a9227fceb5f8b92f5ae77df0cdc82e5891608b/packages/cryptoassets/data/erc20.js#L1680
> 
> Please send your token to your ETH address to see them appear on Ledger Live.

Hi, we did as you wrote. Made a transaction. But YOUC token doesn't appear on Ledger Live. Might be smth should be updated on the user side?

**Comment by TamtamHero** [comment]
This is not the right place, please contact support to ask for ledger-dev slack invite and once there, contact Nafissa-Ledger
