### ISSUE TITLE
Kindly add TOKPIE (TKP) token (ERC20)

### ISSUE THREAD

**Issue by Vasilii79** [LedgerHQ/ledger-dev-doc#39]
Hello, kindly add TOKPIE (TKP) token (ERC20) to the Ledger list: https://www.ledger.com/supported-crypto-assets/
Token name: TOKPIE
Token symbol: TKP
Blockchain: ERC-20 Eethereum
Token smart contract address: 0xd31695a1d35e489252ce57b129fd4b1b05e6acac
Etherscan link: https://etherscan.io/token/0xd31695a1d35e489252ce57b129fd4b1b05e6acac

**Comment by TamtamHero** [comment]
This is not the right place, please contact support to ask for ledger-dev slack invite and once there, contact Nafissa-Ledger

**Comment by Vasilii79** [comment]
> This is not the right place, please contact support to ask for ledger-dev slack invite and once there, contact Nafissa-Ledger

how to contact your support? pls give a link to the right place

**Comment by TamtamHero** [comment]
https://support.ledger.com/hc/en-us/articles/360006554854-How-to-contact-us
