### ISSUE TITLE
Please, add CoinLoan (CLT) token (ERC-20)

### ISSUE THREAD

**Issue by coinloan** [LedgerHQ/ledger-dev-doc#40]
**Token Name:** CoinLoan
**Token Symbol:** CLT
**Blockchain:** ERC-20 (Ethereum)
**Contract Address:** 0x2001f2A0Cf801EcFda622f6C28fb6E10d803D969
**Etherscan:** https://etherscan.io/token/0x2001f2a0cf801ecfda622f6c28fb6e10d803d969

**Comment by TamtamHero** [comment]
This is not the right place, please contact support to ask for ledger-dev slack invite and once there, contact Nafissa-Ledger
