### ISSUE TITLE
Hello, kindly add Yearn Finance Global (YFIG) token (ERC20) to the Ledger list: https://www.ledger.com/supported-crypto-assets/

### ISSUE THREAD

**Issue by YfigFinance** [LedgerHQ/ledger-dev-doc#41]
Hello, kindly add Yearn Finance Global (YFIG) token (ERC20) to the Ledger list: https://www.ledger.com/supported-crypto-assets/
Token name: Yearn Finance Global
Token symbol: YFIG
Blockchain: ERC-20 Eethereum
Token smart contract address: 0xF3a231bF11a0EF1a3074Cf5a1f5620BC85d975Fb
Etherscan link: https://etherscan.io/token/0xF3a231bF11a0EF1a3074Cf5a1f5620BC85d975Fb

**Comment by TamtamHero** [comment]
This is not the right place, please contact support to ask for ledger-dev slack invite and once there, contact Nafissa-Ledger
