### ISSUE TITLE
Kindly add Thousand Token (TND) token waves blockchain.

### ISSUE THREAD

**Issue by thousandtoken** [LedgerHQ/ledger-dev-doc#42]
Hello, kindly add Thousand Token (TND), token of waves to the Ledger
Token name: Thousand Token
Token symbol: TND
Blockchain: Waves
Smart contract address (AssetId): q2xCQyLDKXLzxcMY4PKuFDVknaLoMpq4o57pjJtLMe7
wavesexplorer link: https://wavesexplorer.com/assets/q2xCQyLDKXLzxcMY4PKuFDVknaLoMpq4o57pjJtLMe7

**Comment by TamtamHero** [comment]
This is not the right place, please contact support to ask for ledger-dev slack invite and once there, contact Nafissa-Ledger
