### ISSUE TITLE
Kindly add USER PAY (UP2) token (ERC-20)

### ISSUE THREAD

**Issue by geoinheritance** [LedgerHQ/ledger-dev-doc#44]
Token name: USER PAY
Token symbol: UP2
Blockchain: ERC-20 Ethereum
Token smart contract address: 0x4f54A83f5929a2453c2e18E25B215f6F8F2828F9
Etherscan link: https://etherscan.io/token/0x4f54A83f5929a2453c2e18E25B215f6F8F2828F9

**Comment by TamtamHero** [comment]
This is not the right place, please contact support to ask for ledger-dev invite and contact Nafissa-Ledger there

**Comment by nndiaye-ledger** [comment]
The ERC20 listing has been requested
ETA: 1 month
