### ISSUE TITLE
Kindly add CASINOCOIN (CSC) token (CSCL)

### ISSUE THREAD

**Issue by gitmoluv** [LedgerHQ/ledger-dev-doc#45]
Kindly add CASINOCOIN (CSC) token (CSCL) to the Ledger list: https://www.ledger.com/supported-crypto-assets/

Token name: CASINOCOIN

Token symbol: CSC

Blockchain: Consensus Ledger (Fork of XRP’s codebase (rippled))

Developer Center link:
https://casinocoin.org/build/

Merci 😘

**Comment by TamtamHero** [comment]
This is not the right place, please contact support to ask for ledger-dev slack invite and once there, contact Nafissa-Ledger
