### ISSUE TITLE
Kindly add Sensitrust Token (SETS) token (ERC20)

### ISSUE THREAD

**Issue by sensitrust** [LedgerHQ/ledger-dev-doc#47]
Token name: Sensitrust Token
Token symbol: SETS
Blockchain: ERC-20 Ethereum
Token smart contract address: 0x04E0Af0af1b7f0023c6B12af5a94Df59B0e8cF59
Etherscan link: https://etherscan.io/token/0x04E0Af0af1b7f0023c6B12af5a94Df59B0e8cF59

**Comment by TamtamHero** [comment]
This is not the right place, please contact support to ask for ledger-dev slack invite and once there, contact Nafissa-Ledger

**Comment by FabriceDautriat** [comment]
I'll process it. ETA : 1 month
