### ISSUE TITLE
Unclear instruction: 14x14 icon generation "convert" command

### ISSUE THREAD

**Issue by deanpress** [LedgerHQ/ledger-dev-doc#58]
To generate the 14x14 icon from the 16x16 one, the [instructions](https://github.com/LedgerHQ/ledger-dev-doc/blob/master/source/additional/publishing_an_app.rst#design-guidelines) mention the following:

> Nano X icons must be 14x14 px in size. Developers can create their Nano X icons from the 16x16 px Nano S one with the following command: `convert nanos_app_<token>.gif -crop 14x14+1+1 +repage -negate nanox_app_<token>.gif`

This instruction is unclear.

`convert` using which CLI? Which OS? What package do you need? etc.

**Comment by TamtamHero** [comment]
Like everything in this documentation: Linux
`convert` is part of the `imagemagick` package, i will update the doc to mention it.
